version: '3'

services:
  redis:
    image: 'redis:latest'
  python_netapp:
    image: python_netapp
    container_name: python_netapp
    build:
      context: ./src/
    volumes:
      - ./src:/usr/src/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    extra_hosts:
      - host.docker.internal:host-gateway
  nef_callback_server:
    build:
      context: ./src/nef_callback_server
    ports:
      - 8085:8080
    volumes:
      - ./src/nef_callback_server:/usr/src/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    extra_hosts:
      - host.docker.internal:host-gateway
